version: '3.9'

services:
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    healthcheck:
      test: ['CMD', 'mongo', 'admin', '--port', '27017', '--eval', "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 20
