export const Env = {
  NODE_ENV: 'NODE_ENV',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USERNAME: 'DATABASE_USERNAME',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',
  JWT_SECRET: 'JWT_SECRET',
  BCRYPT_GENERATED_PASSWORD: 'BCRYPT_GENERATED_PASSWORD',
};

export enum Stage {
  PRODUCTION = 'production',
  DEVELOPMENT = 'development',
}
